### ISSUE TITLE
set_keymap fails if X11 is not present.

### ISSUE THREAD

**Issue by vloup** [ArchStrike/archstrike-installer#9]
The code is at https://github.com/ArchStrike/archstrike-installer/blob/master/asinstaller/utils.py#L230

So in a CLI-only environment, you do not have X11 installed and hence you cannot perform the `find` and `setxkbmap` commands.
Alternatives might be to use `localectl` or `loadkeys`.

**Comment by xorond** [comment]
this is an important case for the minimal iso, as it doesn't come with x11 by default
